export default[
    {
        path:'0',
        title:'路由',
        children:[
            {
                path:'/useRouter',
                title:'路由'
            },
            {
                path:'/routerLazyLoad',
                title:'路由懒加载'
            }
        ]
    },
    {
        path:'1',
        title:'HTTP',
        children:[
            {
                path:'/httpVersion',
                title:'HTTP版本'
            },
            {
                path:'/httpHand',
                title:'HTTP握手'
            },
            {
                path:'/stateCode',
                title:'HTTP状态码'
            }
        ]
    },
    {
        path:'2',
        title:'NPM',
        children:[
            {
                path:'/useNpm',
                title:'npm命令行'
            }
        ]
    },
    {
        path:'3',
        title:'动画',
        children:[
            {
                path:'animation',
                title:'动画'
            }
        ]
    },
    {
        path:'4',
        title:'Git',
        children:[
            {
                path:'/gitLine',
                title:'Git命令行'
            }
        ]
    },
    {
        path:'5',
        title:'Store',
        children:[
            {
                path:'/useStore',
                title:'Store'
            }
        ]
    },
    {
        path:'6',
        title:'Axios',
        children:[
            {
                path:'/useAxios',
                title:'Axios'
            }
        ]
    },
    {
        path:'7',
        title:'Directive',
        children:[
            {
                path:'/customerDirective',
                title:'自定义指令'
            }
        ]
    },
    {
        path:'8',
        title:'Cache',
        children:[
            {
                path:'/cacheDetail',
                title:'浏览器缓存'
            }
        ]
    },
    {
        path:'9',
        title:'Performance',
        children:[
            {
                path:'/debounceThrottling',
                title:'防抖节流'
            }
        ]
    },
    {
        path:'twoWayBinding',
        title:'双向绑定'
    },
    {
        path:'/copyType',
        title:'深浅拷贝'
    },
    {
        path:'/dataTypeJudge',
        title:'数据类型判断'
    },
    {
        path:'/elementShow',
        title:'元素显示隐藏'
    },
    {
        path:'/domCssRender',
        title:'DOM与CSS渲染'
    },
    {
        path:'/prototypeProto',
        title:'prototype与__proto__'
    },
    {
        path:'/useNvm',
        title:'nvm'
    },
    {
        path:'10',
        title:'Vue',
        children:[
            {
                path:'/componentImp',
                title:'组件引入'
            },
            {
                path:'/useProps',
                title:'props'
            },
            {
                path:'/refReactiveTorefs',
                title:'ref与reactive与torefs'
            },
            {
                path:'/watch',
                title:'watch'
            },
            {
                path:'/bus',
                title:'bus'
            }
        ]
    },
    {
        path:'/horizontallyAndVerticallyCentered',
        title:'div水平垂直居中'
    },
    {
        path:'/fileUpload',
        title:'打开文件管理器'
    },
    {
        path:'/promise',
        title:'Promise'
    },
    {
        path:'/set',
        title:'设置'
    }
]