/**
 * @description: 菜单路由配置
*/
export default[
    {
        menuName:'首页',
        menuLink:'/home',
        children:null
    },
    {
        menuName:'Echarts',
        menuLink:'/echarts',
        children:[
            {
                menuName:'柱状图',
                menuLink:'/echarts/bar',
                children:[
                    {
                        menuName:'基础柱状图',
                        menuLink:'/echarts/bar/base',
                        children:null
                    },
                    {
                        menuName:'子弹图',
                        menuLink:'/echarts/bar/bullet',
                        children:null
                    },
                    {
                        menuName:'柱状图数据过多展示',
                        menuLink:'/echarts/bar/overShow',
                        children:null
                    }
                ]
            },
            {
                menuName:'折线图',
                menuLink:'/echarts/line',
                children:null
            },
            {
                menuName:'饼图',
                menuLink:'/echarts/pie',
                children:null
            },
            {
                menuName:'多轴图',
                menuLink:'/echarts/multiAxis',
                children:[
                    {
                        menuName:'散点柱状图',
                        menuLink:'/echarts/multiAxis/scatterBar',
                        children:null
                    },
                    {
                        menuName:'线型柱状图',
                        menuLink:'/echarts/multiAxis/lineBar',
                        children:null
                    }
                ]
            }
        ]
    },
    {
        menuName:'Canvas',
        menuLink:'/canvas',
        children:[
            {
                menuName:'雪花',
                menuLink:'/canvas/snowflake',
                children:null
            },
            {
                menuName:'音频可视化',
                menuLink:'/canvas/audioVisualization',
                children:null
            }
        ]
    },
    {
        menuName:'Vue3',
        menuLink:'/vue3',
        children:[
            {
                menuName:'vue-router',
                menuLink:'/vue3/router',
                children:[
                    {
                        menuName:'原理',
                        menuLink:'/vue3/router/principle',
                        children:null
                    },
                    {
                        menuName:'路由使用',
                        menuLink:'/vue3/router/use',
                        children:null
                    },
                    {
                        menuName:'路由懒加载',
                        menuLink:'/vue3/router/lazyLoad',
                        children:null
                    }
                ]
            },
            {
                menuName:'vuex',
                menuLink:'/vue3/vuex',
                children:null
            },
            {
                menuName:'自定义指令',
                menuLink:'/vue3/directive',
                children:null
            },
            {
                menuName:'组件通信',
                menuLink:'/vue3/communication',
                children:[
                    {
                        menuName:'props',
                        menuLink:'/vue3/communication/props',
                        children:null
                    },
                    {
                        menuName:'busEvent',
                        menuLink:'/vue3/communication/busEvent',
                        children:null
                    },
                    {
                        menuName:'provide/inject',
                        menuLink:'/vue3/communication/provideInject',
                        children:null
                    }
                ]
            },
            {
                menuName:'watch',
                menuLink:'/vue3/watch',
                children:null
            },
            {
                menuName:'computed',
                menuLink:'/vue3/computed',
                children:null
            }
        ]
    },
    {
        menuName:'Element-Plus',
        menuLink:'/elementPlus',
        children:[
            {
                menuName:'Popover',
                menuLink:'/elementPlus/popover',
                children:null
            },
            {
                menuName:'upload', //上传
                menuLink:'/elementPlus/upload',
                children:null
            }
        ]
    },
    {
        menuName:'Http',
        menuLink:'/http',
        children:[
            {
                menuName:'http版本',
                menuLink:'/http/version',
                children:null
            },
            {
                menuName:'http握手',
                menuLink:'/http/handshake',
                children:null
            },
            {
                menuName:'http状态码',
                menuLink:'/http/statusCode',
                children:null
            },
            {
                menuName:'浏览器缓存',
                menuLink:'/http/cache',
                children:null
            }
        ]
    },
    // JavaScript
    {
        menuName:'JavaScript',
        menuLink:'/javaScript',
        children:[
            {
                menuName:'手写new',
                menuLink:'/javaScript/new',
                children:null
            },
            {
                menuName:'async/await',
                menuLink:'/javaScript/async',
                children:null
            },
            {
                menuName:'数组转树',
                menuLink:'/javaScript/arrayToTree',
                children:null
            },
            {
                menuName:'判断空对象',
                menuLink:'/javaScript/isEmptyObject',
                children:null
            },
            {
                menuName:'数组去重',
                menuLink:'/javaScript/arrayFilter',
                children:null
            },
            {
                menuName:'setInterval不精确',
                menuLink:'/javaScript/setInterval',
                children:null
            },
            {
                menuName:'Axios',
                menuLink:'/javaScript/axios',
                children:null
            },
            {
                menuName:'this',
                menuLink:'/javaScript/this',
                children:null
            },
            {
                menuName:'原型和原型链',
                menuLink:'/javaScript/proto',
                children:null
            },
            {
                menuName:'闭包',
                menuLink:'/javaScript/closure',
                children:null
            },
            {
                menuName:'作用域',
                menuLink:'/javaScript/scope',
                children:null
            },
            {
                menuName:'异步',
                menuLink:'/javaScript/async',
                children:null
            },
            {
                menuName:'事件循环',
                menuLink:'/javaScript/eventLoop',
                children:null
            },
            {
                menuName:'深浅拷贝',
                menuLink:'/javaScript/copy',
                children:null
            },
            {
                menuName:'防抖节流',
                menuLink:'/javaScript/debounceThrottle',
                children:null
            },
            {
                menuName:'promise',
                menuLink:'/javaScript/promise',
                children:null
            },
            {
                menuName:'generator',
                menuLink:'/javaScript/generator',
                children:null
            },
            {
                menuName:'async/await',
                menuLink:'/javaScript/asyncAwait',
                children:null
            },
            {
                menuName:'模块化',
                menuLink:'/javaScript/module',
                children:null
            },
            {
                menuName:'正则表达式',
                menuLink:'/javaScript/regexp',
                children:null
            },
            {
                menuName:'最小RTT',
                menuLink:'/javaScript/rtt',
                children:null
            },
            {
                menuName:'双向绑定原理',
                menuLink:'/javaScript/doubleBind',
                children:null
            },
            {
                menuName:'发布订阅者模式',
                menuLink:'/javaScript/pubSub',
                children:null
            },
            {
                menuName:'数据类型判断',
                menuLink:'/javaScript/type',
                children:null
            }
        ]
    },
    {
        menuName:'Network',
        menuLink:'/network',
        children:[
            {
                menuName:'TCP握手、挥手',
                menuLink:'/network/tcp',
                children:null
            }
        ]
    },
    // IndexedDB
    {
        menuName:'IndexedDB',
        menuLink:'/indexedDB',
        children:[
            {
                menuName:'基本使用',
                menuLink:'/indexedDB/base',
                children:null
            },
            // {
            //     menuName:'事务',
            //     menuLink:'/indexedDB/transaction',
            //     children:null
            // },
        ]
    },
    {
        menuName:'CSS',
        menuLink:'/css',
        children:[
            {
                menuName:'水平垂直居中',
                menuLink:'/css/center',
                children:null
            },
            {
                menuName:'动画',
                menuLink:'/css/animation',
                children:null
            },
            {
                menuName:'元素显示隐藏',
                menuLink:'/css/display',
                children:null
            },
            {
                menuName:'dom树、css树、render树的区别',
                menuLink:'/css/tree',
                children:null
            },
            {
                menuName:'轮播图',
                menuLink:'/css/carousel',
                children:null
            }
        ]
    },
    {
        menuName:'浏览器',
        menuLink:'/browser',
        children:[
            {
                menuName:'渲染原理',
                menuLink:'/browser/principle',
                children:null
            }
        ]
    },
    {
        menuName:'npm',
        menuLink:'/npm',
        children:null
    },
    {
        menuName:'Nvm',
        menuLink:'/nvm',
        children:null
    },
    {
        menuName:'文件上传',
        menuLink:'/upload',
        children:null
    },
    {
        menuName:'websocket',
        menuLink:'/websocket',
        children:null
    },
    {
        menuName:'Mysql',
        menuLink:'/mysql',
        children:null
    },
    {
        menuName:'Git',
        menuLink:'/git',
        children:null
    }
]